spring:
  application:
    name: business-server

  profiles:
    default: dev

  config:
    import:
      - classpath:dev/application.yml
      - classpath:beta/application-beta.yml
      - classpath:prod/application-prod.yml

  jpa:
    hibernate:
      ddl-auto: update
