spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/theplay
    username: theplay
    password: theplay
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    com.theplay: INFO

server:
  port: 8080
